apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podcidr-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "podcidr-controller.labels" . | nindent 4 }}
    name: podcidr-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "podcidr-controller.selectorLabels" . | nindent 6 }}
      name: podcidr-controller
  template:
    metadata:
      labels:
        name: podcidr-controller
        {{- include "podcidr-controller.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ include "podcidr-controller.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --cluster-cidr={{ .Values.clusterCIDR }}
            - --node-cidr-mask-size={{ .Values.nodeCIDRMaskSize }}
            {{- if .Values.allocateNodeSelector }}
            - --node-selector={{ .Values.allocateNodeSelector }}
            {{- end }}
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect=true
            - --leader-elect-lease-duration={{ .Values.leaderElection.leaseDuration }}
            - --leader-elect-renew-deadline={{ .Values.leaderElection.renewDeadline }}
            - --leader-elect-retry-period={{ .Values.leaderElection.retryPeriod }}
            {{- else }}
            - --leader-elect=false
            {{- end }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
